### ISSUE TITLE
Miss-assigned errors in power-law fit?

### ISSUE THREAD

**Issue by srmcc** [scipy/scipy-cookbook#2]
The current error assignment in the power-law fit is:
indexErr = np.sqrt( covar[0][0] ) 
ampErr = np.sqrt( covar[1][1] ) \* amp

But since index is the first component and amp is the zeroth component:
index = pfinal[1]
amp = 10.0**pfinal[0]
Shouldn't the error assignment be:
indexErr = np.sqrt( covar[1][1] ) 
ampErr = np.sqrt( covar[0][0] ) \* amp
?  Am I missing something obvious?  Thanks!

**Comment by pv** [comment]
This is user-contributed material. You can submit a corrected notebook here.
