### ISSUE TITLE
Trivial misspelling, "completly"

### ISSUE THREAD

**Issue by zunzun** [scipy/scipy-cookbook#3]
"completly" is trivially misspelled

**Comment by rgommers** [comment]
@zunzun care to send a PR to fix it?

**Comment by rgommers** [comment]
otherwise, at least point out where exactly please......

**Comment by zunzun** [comment]
When I use the ghe grep command like so:

find . -type f | xargs grep completly

it yields three file names:

./ipython/robust_regression.ipynb
./ipython/vtkVolumeRendering.ipynb
./originals/vtkVolumeRendering.txt

In a work of this magnitude it is surprising to me that there are so few spelling errors.  Excellent work, and I must say a rather very well written guide.  Top quality.

James

**Comment by rgommers** [comment]
Thanks @zunzun. The cookbook is all user contributed code/docs, so credits go to those that contributed.
