### ISSUE TITLE
Alternative / Suggestion for Incorperation

### ISSUE THREAD

**Issue by Joeb34** [scipy/scipy-cookbook#34]
https://github.com/ml31415/numpy-groupies is similar to the matlab accumarray in some ways - and its fast. 

As an Alternative to accum refrenced in AccumarrayLike.ipynb

**Comment by rgommers** [comment]
@Joeb34 feel free to submit a PR. This is a community-driven repo, we don't implement suggestions in issues unless they're major bugs/problems.

I'll close this issue since we won't take action ourselves

**Comment by Joeb34** [comment]
Thanks for the suggestion!
