### ISSUE TITLE
Incorrect variable used in RadialBasisFunctions.ipynb

### ISSUE THREAD

**Issue by chalmersgit** [scipy/scipy-cookbook#36]
In the 1D example, when plotting the two curves, it plots the same curve twice.

On line 58:
plt.plot(xi, yi, 'g')
Should be:
plt.plot(xi, fi, 'g')

I would do a pull request but this would require updating the image as well, and I'm not able to produce the image without the title of the RBF curve overlapping with the xticks of the first curve.

**Comment by cassiasamp** [comment]
Hello, I changed the yi to fi and fixed the overlapping with plt.tight_layout().
This is the link to the pull request with the fixed notebook: https://github.com/scipy/scipy-cookbook/pull/40
