### ISSUE TITLE
Small but important correction

### ISSUE THREAD

**Issue by BenSandeen** [scipy/scipy-cookbook#7]
In the section titled "Parallel Programming with numpy and scipy" in ParallelProgramming.ipynb, there's statement that while true in most cases, is not universally valid: "Using a multicore machine will provide at best a speedup by a factor of the number of cores available."

For things like searching a tree, depending on where the sought-after node is, it is possible to observe speedups of factors far greater than the number of cores available.

**Comment by pv** [comment]
This is user-contributed material, and content changes are best made via pull requests directly to the texts.
